---
# Replace the MAC with the real NIC MAC of worker02.
worker_ip: 10.0.0.12
worker_mac: "88:a2:9e:9a:ba:c7"
board: "Raspberry Pi 5"
arch: arm64
cpus: 4
memory: 8192
cores: 4
threads: 1
has_gpu: false
