---
# Replace the MAC with the real NIC MAC of worker04.
# This node is a Jetson Orin Nano 8GB. nvidia-smi works and NVML/GPU autodetection is enabled.
worker_ip: 10.0.0.14
worker_mac: "3c:6d:66:bf:29:f7"
board: "Jetson Orin Nano"
arch: arm64
cpus: 6
memory: 8192
cores: 6
threads: 1
has_gpu: true
gpus: 1
gres_file: /dev/nvgpu
